sudo: required
services:
  - docker

before_install:
  - docker build -t thilina9718/docker-react-demo -f Dockerfile.dev .

script:
  - docker run thilina9718/docker-react-demo npm run test -- --coverage